[package]
name = "notes_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dialoguer = "0.11.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
thiserror = "1.0.63"
