[package]
name = "notes_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dialoguer = "0.11.0"
itertools = "0.13.0"
lazy_static = "1.5.0"
rand = "0.8.5"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
thiserror = "1.0.63"
